邮件和短域名
UniqueStudio/open-platform pull request #7
Opened 2021-01-21 12:47 UTC by nothatDinger

邮件加了抄送和密抄，接口有相应的增加改变

加了个短域名服务，
生成短链的接口为/genurl
需要传入带urllist字段，值为url数组的json

解析短链的接口为/v/:shorturl

2021-01-21 13:27 UTC, wangnengjie commented
LGTM. I give you the write permission. You can push to this repo if you have any update commits laster. You can use `sync.waitGroup` and channel with cache to make your code better. 
And I wonder what's the use for `ShortUrl` and `HashCode` fields in struct `shorter`?
https://github.com/nothatDinger/open-platform/blob/a7e417719f160527fc53aa029bef753705111e6d/handler/genshorturl.go#L26

2021-01-21 13:33 UTC, nothatDinger commented
Actually they are useless ,I'll delete them in update commit soon



---原始邮件---
发件人: "Panda"<notifications@github.com&gt;
发送时间: 2021年1月21日(周四) 晚上9:27
收件人: "UniqueStudio/open-platform"<open-platform@noreply.github.com&gt;;
抄送: "nothatDinger"<578279246@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [UniqueStudio/open-platform] 邮件和短域名 (#7)




 
LGTM. I give you the write permission. You can push to this repo if you have any update commits laster. You can use sync.waitGroup and channel with cache to make your code better.
 And I wonder what's the use for ShortUrl and HashCode fields in struct shorter?
 https://github.com/nothatDinger/open-platform/blob/a7e417719f160527fc53aa029bef753705111e6d/handler/genshorturl.go#L26
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-21 13:54 UTC, ttzztztz requested changes

2021-01-21 13:54 UTC, ttzztztz commented on db/mysql.go
> +	err = ORM.Sync(new(Reply), new(Status),new(Short_Url))
one more `backspace`, pay attention to the code-style

2021-01-21 13:54 UTC, ttzztztz commented on handler/genshorturl.go
> +	err error
one more `backspace`, pay attention to the code-style.

You can use the code format tool in the IDE

2021-01-21 13:54 UTC, ttzztztz commented on handler/genshorturl.go
> +
remove this line

2021-01-21 13:54 UTC, ttzztztz commented on handler/genshorturl.go
> +		}else{
code-style

2021-01-21 13:54 UTC, ttzztztz commented on handler/genshorturl.go
> +		if count == len(urlList) {
use `sync.WaitGroup` in the golang standard library instead

2021-01-21 13:54 UTC, ttzztztz commented on handler/mail.go
> +	bccto :=data.BccTo
pay attention to the code style. One more `backspace`

2021-01-21 13:54 UTC, ttzztztz commented on handler/mail.go
> +	ccto :=data.CcTo
pay attention to the code style. One more `backspace`

2021-01-21 13:54 UTC, ttzztztz commented on handler/mail.go
> +		subject, renderContent, "html", utils.RemoveDuplicate(append(toList, to)),ccto,bccto)
pay attention to the code style. Two more `backspace`

2021-01-21 13:54 UTC, ttzztztz commented on handler/mail.go
> +func SendToMail(user, password, host, subject, body, mailtype string, to,ccto,bccto []string) error {
pay attention to the code style. Two more `backspace`

2021-01-21 13:54 UTC, ttzztztz commented on handler/mail.go
> +func MergeSlice(s1 []string, s2 []string) []string {
Use `append` method in the standard library and `...` operator instead.
You can find references at https://www.geeksforgeeks.org/how-to-append-a-slice-in-golang/

Don't write a method that already exists in the standard library

2021-01-21 13:54 UTC, ttzztztz commented on handler/shorturl.go
> +	shorturl :=  c.Param("Shorturl")
code style

2021-01-21 13:54 UTC, ttzztztz commented on handler/shorturl.go
> +	has,err:=db.ORM.Where("Shorturl=?",shorturl).Get(&result)
code style

2021-01-21 13:54 UTC, ttzztztz commented on handler/shorturl.go
> +	if err !=nil {
code style

2021-01-21 13:54 UTC, ttzztztz commented on main.go
> +	r.GET("/genUrl",middleware.Auth(),handler.CreateShortUrlHandler)
code style

2021-01-21 13:54 UTC, ttzztztz commented on utils/config.go
> +		Host      string `default:"127.0.0.1";yaml:"host"`
The spliter of golang struct tag is ` ` (backspace), not `;`

Reference
https://medium.com/golangspec/tags-in-golang-3e5db0b8ef3e
https://stackoverflow.com/questions/18635671/how-to-define-multiple-name-tags-in-a-struct

2021-01-21 14:24 UTC, wangnengjie commented
Why a binary file "open-platform" here?
https://github.com/UniqueStudio/open-platform/pull/7/files#diff-ef0c3328876d5e5355d13903a4e2a2f618c85da9f4e3cd652cbfebf3a9db57ef

2021-01-22 08:29 UTC, ttzztztz requested changes

2021-01-22 08:29 UTC, ttzztztz commented on utils/config.go
> +		Host      string `default:"127.0.0.1",yaml:"host"`
`default:"127.0.0.1" yaml:"host"`

2021-01-22 08:30 UTC, ttzztztz commented on utils/config.go
> +		Host      string `default:"127.0.0.1",yaml:"host"`
Other similarities

2021-01-22 08:31 UTC, nothatDinger commented on utils/config.go
> +		Host      string `default:"127.0.0.1",yaml:"host"`
ok

2021-02-07 14:34 UTC, merged